/**
 * Maps Microsoft Graph delegated (scp) or application (roles) permission names on an access token
 * to m365-agent-cli feature areas with read vs write coverage.
 *
 * @see docs/GRAPH_SCOPES.md
 * @see docs/GRAPH_PERMISSION_FEATURE_MATRIX.md (generated by `npm run docs:graph-permission-matrix`)
 *
 * **Doc generation:** Keep {@link CapabilityMatrixRow.detail} free of raw `|` characters (use ` / ` for alternatives);
 * they break the Markdown pipe-table in that doc.
 */

export type TokenPermissionKind = 'delegated' | 'application' | 'mixed' | 'unknown';

export interface GraphTokenPayloadForCapabilities {
  scp?: string;
  roles?: string[];
}

export interface CapabilityMatrixRow {
  id: string;
  /** Short group label */
  area: string;
  /** One-line CLI context */
  detail: string;
  /** Scopes that satisfy read access (any one). Write scopes count toward read only when {@link readColumnDash} is false. */
  readScopes: string[];
  /** Scopes that satisfy write/mutate access (any one). */
  writeScopes: string[];
  /** When true, row is informational (e.g. EWS not represented in Graph token). */
  notApplicable?: boolean;
  /** Read column shows — (not a meaningful read/write pair for this area). */
  readColumnDash?: boolean;
  /** Write column shows — */
  writeColumnDash?: boolean;
  /**
   * Overrides the generated “Read” cell in `docs/GRAPH_PERMISSION_FEATURE_MATRIX.md`
   * (see `scripts/generate-graph-permission-feature-matrix.ts`).
   */
  docFeatureMatrixReadCell?: string;
  /**
   * Overrides the generated “Write” cell in `docs/GRAPH_PERMISSION_FEATURE_MATRIX.md`.
   */
  docFeatureMatrixWriteCell?: string;
  /** Appended after the generated read scope list in that doc (e.g. permission-type hint). */
  docFeatureMatrixReadSuffix?: string;
}

/** Build permission set from JWT payload (`scp` space-separated and/or `roles` array). */
export function permissionSetFromGraphPayload(payload: GraphTokenPayloadForCapabilities): Set<string> {
  const out = new Set<string>();
  if (typeof payload.scp === 'string' && payload.scp.trim()) {
    for (const s of payload.scp.split(/\s+/)) {
      if (s) out.add(s);
    }
  }
  if (Array.isArray(payload.roles)) {
    for (const r of payload.roles) {
      if (typeof r === 'string' && r.trim()) out.add(r.trim());
    }
  }
  return out;
}

export function graphTokenPermissionKind(payload: GraphTokenPayloadForCapabilities): TokenPermissionKind {
  const hasScp = typeof payload.scp === 'string' && payload.scp.trim().length > 0;
  const hasRoles = Array.isArray(payload.roles) && payload.roles.length > 0;
  if (hasScp && hasRoles) return 'mixed';
  if (hasScp) return 'delegated';
  if (hasRoles) return 'application';
  return 'unknown';
}

function hasAnyPermission(perms: Set<string>, candidates: string[]): boolean {
  return candidates.some((c) => perms.has(c));
}

export interface EvaluatedCapability extends CapabilityMatrixRow {
  readOk: boolean;
  writeOk: boolean;
}

function evaluateRow(perms: Set<string>, row: CapabilityMatrixRow): EvaluatedCapability {
  if (row.notApplicable) {
    return { ...row, readOk: false, writeOk: false };
  }
  const readFromRead = hasAnyPermission(perms, row.readScopes);
  const readFromWrite = row.readColumnDash ? false : hasAnyPermission(perms, row.writeScopes);
  const readOk = readFromRead || readFromWrite;
  const writeOk = row.writeColumnDash ? false : hasAnyPermission(perms, row.writeScopes);
  return { ...row, readOk, writeOk };
}

/**
 * Ordered rows for CLI / JSON output. Read is satisfied by any read scope or any listed write scope
 * (e.g. `Calendars.ReadWrite` unlocks calendar read).
 */
export const GRAPH_CAPABILITY_MATRIX: readonly CapabilityMatrixRow[] = [
  {
    id: 'profile',
    area: 'Profile / sign-in',
    detail: '`whoami`, basic `/me`',
    readScopes: ['User.Read', 'User.ReadWrite'],
    writeScopes: ['User.ReadWrite']
  },
  {
    id: 'directory',
    area: 'Directory users',
    detail: '`find` user/group search; `org user` — often admin consent for `/users` reads',
    readScopes: ['User.Read.All', 'Directory.Read.All', 'Directory.ReadWrite.All'],
    writeScopes: ['Directory.ReadWrite.All']
  },
  {
    id: 'org.relations',
    area: 'Org hierarchy & profile',
    detail:
      '`org manager`, `direct-reports`, `user`, `transitive-reports` — self with `User.Read`; others typically `User.Read.All`',
    readScopes: ['User.Read', 'User.Read.All', 'Directory.Read.All', 'Directory.ReadWrite.All'],
    writeScopes: []
  },
  {
    id: 'calendar.own',
    area: 'Calendar (your mailbox)',
    detail: '`calendar`, `create-event`, `respond`, …',
    readScopes: ['Calendars.Read', 'Calendars.ReadWrite'],
    writeScopes: ['Calendars.ReadWrite']
  },
  {
    id: 'calendar.shared',
    area: 'Calendar (shared / delegated)',
    detail: '`calendar --mailbox`, delegated calendars',
    readScopes: ['Calendars.Read.Shared', 'Calendars.ReadWrite.Shared'],
    writeScopes: ['Calendars.ReadWrite.Shared']
  },
  {
    id: 'mail.own',
    area: 'Mail (your mailbox)',
    detail: '`mail`, `folders`, `drafts` (Graph path)',
    readScopes: ['Mail.Read', 'Mail.ReadWrite'],
    writeScopes: ['Mail.ReadWrite']
  },
  {
    id: 'mail.shared',
    area: 'Mail (shared / delegated)',
    detail: '`mail --mailbox`, shared folders',
    readScopes: ['Mail.Read.Shared', 'Mail.ReadWrite.Shared'],
    writeScopes: ['Mail.ReadWrite.Shared']
  },
  {
    id: 'mail.send',
    area: 'Send mail (Graph)',
    detail: '`send` — `Mail.Send` alone can send; read mail needs `Mail.ReadWrite`',
    readScopes: [],
    writeScopes: ['Mail.Send', 'Mail.ReadWrite'],
    readColumnDash: true
  },
  {
    id: 'mailbox.settings',
    area: 'Mailbox settings',
    detail: '`oof`, categories, mailbox settings',
    readScopes: ['MailboxSettings.Read', 'MailboxSettings.ReadWrite'],
    writeScopes: ['MailboxSettings.ReadWrite']
  },
  {
    id: 'rooms',
    area: 'Rooms & places',
    detail: '`rooms` (lists, rooms, find, get), `find --rooms`, Places in `create-event`',
    readScopes: ['Place.Read.All'],
    writeScopes: []
  },
  {
    id: 'people',
    area: 'People / relevance',
    detail: '`people` list / get, `find` (People + directory users)',
    readScopes: ['People.Read', 'People.Read.All'],
    writeScopes: []
  },
  {
    id: 'files.onedrive',
    area: 'OneDrive / files',
    detail:
      '`files` (delta, shared-with-me, thumbnails, list-item, follow, sensitivity-assign/extract, retention-label, permanent-delete, copy/move, invite, permissions), `excel` workbooks (tables/pivots/ranges/sessions/application) + beta comments, `word`/`powerpoint` full per-item mirror + preview/meta/download/thumbnails',
    readScopes: ['Files.Read', 'Files.Read.All', 'Files.ReadWrite', 'Files.ReadWrite.All'],
    writeScopes: ['Files.ReadWrite', 'Files.ReadWrite.All']
  },
  {
    id: 'sharepoint.sites',
    area: 'SharePoint sites',
    detail:
      '`sharepoint` resolve-site/get-site/drives/lists/get-list/columns/items (OData paging)/create/update/get/delete, `items-delta`, followed sites; `site-pages`',
    readScopes: ['Sites.Read.All', 'Sites.ReadWrite.All', 'Sites.Manage.All'],
    writeScopes: ['Sites.ReadWrite.All', 'Sites.Manage.All']
  },
  {
    id: 'sharepoint.followed',
    area: 'SharePoint followed sites',
    detail: '`sharepoint followed-sites`, `follow`, `unfollow`',
    readScopes: ['Sites.Read.All', 'Sites.ReadWrite.All'],
    writeScopes: ['Sites.ReadWrite.All']
  },
  {
    id: 'insights',
    area: 'Discovery / Insights',
    detail: '`insights` trending / used / shared, `files recent`, `files activities`, `files preview`',
    readScopes: [
      'Sites.Read.All',
      'Sites.ReadWrite.All',
      'Files.Read',
      'Files.Read.All',
      'Files.ReadWrite',
      'Files.ReadWrite.All'
    ],
    writeScopes: []
  },
  {
    id: 'viva',
    area: 'Viva / employee experience (Graph beta)',
    detail:
      '`viva` — user + tenant `/employeeExperience` (communities, goals, learning, roles), work time + insights, admin/org itemInsights, workHoursAndLocations, meeting Engage Q&A',
    readScopes: [
      'User.Read',
      'LearningAssignedCourse.Read',
      'EngagementRole.Read',
      'EngagementRole.Read.All',
      'MailboxSettings.Read',
      'MailboxSettings.ReadWrite'
    ],
    writeScopes: ['EngagementRole.ReadWrite.All', 'MailboxSettings.ReadWrite', 'User.ReadWrite', 'User.ReadWrite.All'],
    docFeatureMatrixReadSuffix:
      ' — tenant learning / communities / goals need product-specific admin-consented scopes per Microsoft; work-time mutations may be app-only (`Schedule-WorkingTime.*`) in some tenants'
  },
  {
    id: 'approvals',
    area: 'Approvals',
    detail:
      '`approvals` list / get / steps / respond / cancel (DELETE) — Teams Approvals + Power Automate (beta `/me/approvals`); `ApprovalSolution.ReadWrite` (canonical) or narrower `ApprovalSolutionResponse.ReadWrite`',
    readScopes: [
      'ApprovalSolution.Read.All',
      'ApprovalSolution.ReadWrite',
      'ApprovalSolution.ReadWrite.All',
      'ApprovalSolutionResponse.ReadWrite'
    ],
    writeScopes: ['ApprovalSolution.ReadWrite', 'ApprovalSolutionResponse.ReadWrite']
  },
  {
    id: 'todo',
    area: 'Microsoft To Do',
    detail:
      '`todo` (incl. `attachment-session` list/get/patch/delete/content-*; `root` get/patch/delete for …/todo — destructive delete requires `--confirm`)',
    readScopes: ['Tasks.Read', 'Tasks.ReadWrite'],
    writeScopes: ['Tasks.ReadWrite']
  },
  {
    id: 'planner.groups',
    area: 'Planner & group-backed Teams',
    detail:
      '`planner` (incl. `delete-plan-details`, `delete-task-details`), `teams` members/channels/apps/tabs — broad group scope',
    readScopes: ['Group.Read.All', 'Group.ReadWrite.All'],
    writeScopes: ['Group.ReadWrite.All']
  },
  {
    id: 'groups.outlook',
    area: 'Outlook Groups (Microsoft 365 groups)',
    detail: '`groups list`, `conversations`, `thread`, `posts`, `post-reply`',
    readScopes: ['Group.Read.All', 'Group.ReadWrite.All'],
    writeScopes: ['Group.ReadWrite.All']
  },
  {
    id: 'contacts.own',
    area: 'Contacts (your mailbox)',
    detail: '`contacts` (extensions: `-f/--folder`, `--child-folder` for nested contact folder paths)',
    readScopes: ['Contacts.Read', 'Contacts.ReadWrite'],
    writeScopes: ['Contacts.ReadWrite']
  },
  {
    id: 'contacts.shared',
    area: 'Contacts (shared mailbox)',
    detail: '`contacts --user` (extensions: `-f/--folder`, `--child-folder`)',
    readScopes: ['Contacts.Read.Shared', 'Contacts.ReadWrite.Shared'],
    writeScopes: ['Contacts.ReadWrite.Shared']
  },
  {
    id: 'contacts.mergeSuggestions',
    area: 'Contact merge suggestions (Graph beta)',
    detail:
      '`contacts merge-suggestions` get/set/delete — `/settings/contactMergeSuggestions` (see Microsoft Graph beta docs for exact permission names)',
    readScopes: ['User.Read', 'User.ReadWrite', 'User.Read.All'],
    writeScopes: ['User.ReadWrite', 'User.ReadWrite.All']
  },
  {
    id: 'meetings.online',
    area: 'Online meetings',
    detail: '`meeting`, Teams links in `create-event`',
    readScopes: ['OnlineMeetings.Read', 'OnlineMeetings.ReadWrite'],
    writeScopes: ['OnlineMeetings.ReadWrite']
  },
  {
    id: 'meetings.recordings',
    area: 'Meeting recordings',
    detail:
      '`meeting recordings`, `recording-download`, `recordings-all` (+ `--delta`) — tenant Stream/Teams policy applies',
    readScopes: ['OnlineMeetingRecording.Read.All'],
    writeScopes: []
  },
  {
    id: 'meetings.transcripts',
    area: 'Meeting transcripts',
    detail: '`meeting transcripts`, `transcript-download`, `transcripts-all` (+ `--delta`)',
    readScopes: ['OnlineMeetingTranscript.Read.All'],
    writeScopes: []
  },
  {
    id: 'onenote',
    area: 'OneNote',
    detail: '`onenote`',
    readScopes: ['Notes.Read', 'Notes.ReadWrite', 'Notes.ReadWrite.All'],
    writeScopes: ['Notes.ReadWrite', 'Notes.ReadWrite.All']
  },
  {
    id: 'teams.core',
    area: 'Teams (teams & channels)',
    detail: '`teams` list (incl. `list --user`), channels, `channel-files-folder`, metadata',
    readScopes: ['Team.ReadBasic.All', 'Channel.ReadBasic.All'],
    writeScopes: []
  },
  {
    id: 'teams.channel.messages',
    area: 'Teams channel messages',
    detail: '`teams messages`, read channel posts — often admin consent',
    readScopes: ['ChannelMessage.Read.All'],
    writeScopes: []
  },
  {
    id: 'teams.channel.send',
    area: 'Teams channel send',
    detail:
      '`teams channel-message-send`, replies, `channel-message-patch`, `channel-message-delete` (soft/hard), `tab-create` / `tab-update` / `tab-delete`',
    readScopes: [],
    writeScopes: ['ChannelMessage.Send'],
    readColumnDash: true
  },
  {
    id: 'teams.chats',
    area: 'Teams chats (1:1 / group)',
    detail:
      '`teams chats`, messages, `chat-create`, `chat-member-add`, `chat-message-patch`, `chat-message-delete`, `chat-apps` / `chat-app-*`',
    readScopes: ['Chat.Read', 'Chat.ReadWrite'],
    writeScopes: ['Chat.ReadWrite']
  },
  {
    id: 'teams.activity',
    area: 'Teams activity feed',
    detail:
      '`teams activity-notify` — POST /me/teamwork/sendActivityNotification, /chats/{id}/sendActivityNotification, or /users/{id}/teamwork/sendActivityNotification (--user-id; typically app token)',
    readScopes: [],
    writeScopes: ['TeamsActivity.Send'],
    readColumnDash: true
  },
  {
    id: 'teams.members.write',
    area: 'Teams membership (provision)',
    detail: '`teams team-member-add`, `teams channel-member-add`',
    readScopes: [],
    writeScopes: [
      'TeamMember.ReadWrite.All',
      'TeamMember.ReadWriteNonGuestRole.All',
      'ChannelMember.ReadWrite.All',
      'Group.ReadWrite.All'
    ],
    readColumnDash: true
  },
  {
    id: 'teams.apps.catalog',
    area: 'Teams app catalog',
    detail: '`teams app-catalog`, `teams app-catalog-get`',
    readScopes: ['AppCatalog.Read.All', 'AppCatalog.Submit'],
    writeScopes: []
  },
  {
    id: 'teams.apps.team',
    area: 'Teams apps on a team',
    detail: '`teams apps`, `app-get`, `app-add`, `app-patch`, `app-upgrade`, `app-delete`',
    readScopes: ['Group.ReadWrite.All'],
    writeScopes: ['Group.ReadWrite.All']
  },
  {
    id: 'teams.apps.personal',
    area: 'Teams apps (personal user scope)',
    detail:
      '`teams user-apps`, `user-app-get`, `user-app-add`, `user-app-delete` (`--user` may need broader Teams app permissions)',
    readScopes: ['TeamsAppInstallation.ReadWriteSelfForUser'],
    writeScopes: ['TeamsAppInstallation.ReadWriteSelfForUser']
  },
  {
    id: 'presence.read',
    area: 'Presence (read)',
    detail: '`presence me`, `presence user`, bulk',
    readScopes: ['Presence.Read.All'],
    writeScopes: []
  },
  {
    id: 'presence.write',
    area: 'Presence (set/clear)',
    detail:
      '`presence set-*`, `presence clear-*`, `status-message-set`, `preferred-set`, `preferred-clear`, `clear-location`',
    readScopes: [],
    writeScopes: ['Presence.ReadWrite'],
    readColumnDash: true
  },
  {
    id: 'bookings',
    area: 'Bookings',
    detail: '`bookings`',
    readScopes: ['Bookings.Read.All', 'Bookings.ReadWrite.All'],
    writeScopes: ['Bookings.ReadWrite.All']
  },
  {
    id: 'graph.search',
    area: 'Graph Search',
    detail:
      '`graph-search` — presets/types, `--merge-json-file` / `--body-file`, entity-specific mail/files/site scopes',
    readScopes: [
      'Mail.Read',
      'Mail.ReadWrite',
      'Files.Read.All',
      'Files.ReadWrite.All',
      'Sites.Read.All',
      'Sites.ReadWrite.All'
    ],
    writeScopes: []
  },
  {
    id: 'copilot.retrieval',
    area: 'Copilot Retrieval API',
    detail: '`copilot retrieval` — SharePoint/OneDrive need Files+Sites read; connectors need `ExternalItem.Read.All`',
    readScopes: [
      'Files.Read.All',
      'Files.ReadWrite.All',
      'Sites.Read.All',
      'Sites.ReadWrite.All',
      'ExternalItem.Read.All'
    ],
    writeScopes: []
  },
  {
    id: 'copilot.search',
    area: 'Copilot Search API (preview)',
    detail: '`copilot search` — OneDrive; `Files.Read.All`+`Sites.Read.All` (or ReadWrite equivalents)',
    readScopes: ['Files.Read.All', 'Files.ReadWrite.All', 'Sites.Read.All', 'Sites.ReadWrite.All'],
    writeScopes: []
  },
  {
    id: 'copilot.chat',
    area: 'Copilot Chat API (preview)',
    detail:
      '`copilot conversation-create`, `conversations-list`, `conversation-*`, `messages-*`, `chat`, `chat-stream` (OData actions) — Microsoft requires the full permission bundle documented for Chat API',
    readScopes: [
      'Sites.Read.All',
      'Sites.ReadWrite.All',
      'Mail.Read',
      'Mail.ReadWrite',
      'Mail.ReadWrite.Shared',
      'People.Read.All',
      'OnlineMeetingTranscript.Read.All',
      'Chat.Read',
      'Chat.ReadWrite',
      'ChannelMessage.Read.All',
      'ExternalItem.Read.All'
    ],
    writeScopes: []
  },
  {
    id: 'copilot.interactions',
    area: 'Copilot interaction export',
    detail:
      '`copilot interactions-export`, `interactions-export-tenant` — application `AiEnterpriseInteraction.Read.All` (delegated not supported)',
    readScopes: ['AiEnterpriseInteraction.Read.All'],
    writeScopes: [],
    docFeatureMatrixReadSuffix: ' (application permission typical)'
  },
  {
    id: 'copilot.interactions.notify',
    area: 'Copilot interaction change notifications',
    detail:
      '`subscribe copilot-interactions` — delegated `AiEnterpriseInteraction.Read` (per-user); tenant subscription is app-only',
    readScopes: ['AiEnterpriseInteraction.Read', 'AiEnterpriseInteraction.Read.All'],
    writeScopes: []
  },
  {
    id: 'copilot.meetingInsights',
    area: 'Copilot meeting insights',
    detail:
      '`copilot meeting-insights-list`, `meeting-insight-get`, `meeting-insights-count`, `meeting-insight-create|patch|delete`',
    readScopes: ['OnlineMeetingAiInsight.Read.All'],
    writeScopes: []
  },
  {
    id: 'copilot.reports',
    area: 'Copilot usage reports',
    detail:
      '`copilot reports user-count-*`, `usage-user-detail`, `nav-get|nav-patch|nav-delete` — `Reports.Read.All` + admin reader role per Microsoft',
    readScopes: ['Reports.Read.All'],
    writeScopes: []
  },
  {
    id: 'copilot.packages',
    area: 'Copilot package catalog (admin)',
    detail:
      '`copilot packages` list|get|create|delete|zip-download|zip-upload|update|block|unblock|reassign — `CopilotPackages.Read*.`',
    readScopes: ['CopilotPackages.Read.All', 'CopilotPackages.ReadWrite.All'],
    writeScopes: ['CopilotPackages.ReadWrite.All']
  },
  {
    id: 'copilot.agents',
    area: 'Copilot agents (Graph)',
    detail: '`copilot agents-list`, `agent-get` — permissions per Microsoft Graph `/copilot/agents` docs',
    readScopes: [],
    writeScopes: [],
    readColumnDash: true
  },
  {
    id: 'copilot.settings',
    area: 'Copilot user settings',
    detail:
      '`copilot settings-*` (+ `settings-delete`, `settings-people-delete`, `settings-enhanced-personalization-delete`)',
    readScopes: [],
    writeScopes: [],
    readColumnDash: true
  },
  {
    id: 'copilot.adminSettings',
    area: 'Copilot admin settings',
    detail:
      '`copilot admin-settings-*`, `admin-limited-mode-*`, `admin-settings-delete`, `admin-limited-mode-delete`, `admin-nav-*`, `admin-catalog-*` (beta)',
    readScopes: [],
    writeScopes: [],
    readColumnDash: true
  },
  {
    id: 'copilot.activityFeed',
    area: 'Copilot realtime activity feed',
    detail:
      '`copilot activity-feed …` incl. `patch-root`, `delete-root`, `*-count` — `/copilot/communications/realtimeActivityFeed/...`',
    readScopes: [],
    writeScopes: [],
    readColumnDash: true
  },
  {
    id: 'copilot.aiUser',
    area: 'Copilot aiUser (/copilot/users)',
    detail: '`copilot ai-user …` — list/count/CRUD, interactionHistory, onlineMeetings',
    readScopes: [],
    writeScopes: [],
    readColumnDash: true
  },
  {
    id: 'graph.invoke',
    area: 'Graph invoke / batch',
    detail: '`graph invoke`, `graph batch` — depends on path you call',
    readScopes: [],
    writeScopes: [],
    readColumnDash: true,
    writeColumnDash: true,
    docFeatureMatrixReadCell: '*Depends on URL and method*',
    docFeatureMatrixWriteCell: '*Depends on URL and method*'
  },
  {
    id: 'ews',
    area: 'Exchange Web Services (EWS)',
    detail:
      'EWS mail/calendar when configured — not in Graph `scp`; add `EWS.AccessAsUser.All` (Exchange Online) on the same Entra app',
    readScopes: [],
    writeScopes: [],
    notApplicable: true,
    docFeatureMatrixReadCell: '*Not in Graph `scp`*',
    docFeatureMatrixWriteCell: '*Not in Graph `scp`* — add `EWS.AccessAsUser.All`'
  }
];

export function evaluateGraphCapabilities(perms: Set<string>): EvaluatedCapability[] {
  return GRAPH_CAPABILITY_MATRIX.map((row) => evaluateRow(perms, row));
}

function checkbox(ok: boolean): string {
  return ok ? '[x]' : '[ ]';
}

/** Human-readable table: Feature | Read | Write (Write shows — when no write scopes apply). */
export function formatCapabilityTextTable(evaluated: EvaluatedCapability[], opts?: { verbose?: boolean }): string {
  const colW = 38;
  const lines: string[] = [];
  lines.push(`${'Feature'.padEnd(colW)} Read   Write`);
  lines.push('─'.repeat(colW + 14));
  for (const r of evaluated) {
    let readCell: string;
    if (r.notApplicable || r.readColumnDash) {
      readCell = ' —  ';
    } else {
      readCell = `${checkbox(r.readOk)} `.padEnd(5);
    }
    let writeCell: string;
    if (r.notApplicable || r.writeColumnDash) {
      writeCell = ' —';
    } else if (r.writeScopes.length === 0) {
      writeCell = ' —';
    } else {
      writeCell = checkbox(r.writeOk);
    }
    lines.push(`${r.area.padEnd(colW)} ${readCell} ${writeCell}`);
    if (opts?.verbose) {
      lines.push(`  ${r.detail}`);
    }
  }
  return lines.join('\n');
}
