import type { GraphResponse } from './graph-client.js';
import { callGraph, GraphApiError, graphError, graphResult } from './graph-client.js';
import { graphUserPath } from './graph-user-path.js';

function inboxRulesBase(user?: string): string {
  return `${graphUserPath(user, 'mailFolders/inbox/messageRules')}`;
}

export interface MessageRuleCondition {
  /** Strings the message body contains (case-insensitive) */
  bodyContains?: string[];
  /** Strings the message subject contains (case-insensitive) */
  subjectContains?: string[];
  /** Strings the message sender contains (case-insensitive) */
  senderContains?: string[];
  /** Strings any recipient contains (case-insensitive) */
  recipientContains?: string[];
  /** Senders to match */
  fromAddresses?: { emailAddress: { name?: string; address: string } }[];
  /** Recipients to match */
  sentToAddresses?: { emailAddress: { name?: string; address: string } }[];
  /** Message has attachments */
  hasAttachments?: boolean;
  /** Importance: low | normal | high */
  importance?: 'Low' | 'Normal' | 'High';
  /** Message is an automatic forward */
  isAutomaticForward?: boolean;
}

export interface MessageRuleAction {
  /** Move message to this folder (name or well-known name) */
  moveToFolder?: string;
  /** Copy message to this folder */
  copyToFolder?: string;
  /** Soft-delete the message */
  delete?: boolean;
  /** Permanently delete the message */
  permanentDelete?: boolean;
  /** Mark as read */
  markAsRead?: boolean;
  /** Set importance: low | normal | high */
  markImportance?: 'Low' | 'Normal' | 'High';
  /** Forward to these recipients */
  forwardToRecipients?: { emailAddress: { name?: string; address: string } }[];
  /** Forward as attachment to these recipients */
  forwardAsAttachmentToRecipients?: { emailAddress: { name?: string; address: string } }[];
  /** Assign categories */
  assignCategories?: string[];
  /** Stop processing more rules */
  stopProcessingRules?: boolean;
}

export interface MessageRule {
  id: string;
  displayName: string;
  priority: number;
  isEnabled: boolean;
  conditions?: MessageRuleCondition;
  actions?: MessageRuleAction;
  exceptionConditions?: MessageRuleCondition;
  /** Human-readable description auto-generated by Exchange */
  ruleDescription?: string;
}

interface MessageRuleListResponse {
  value: MessageRule[];
}

export interface CreateMessageRulePayload {
  displayName: string;
  priority?: number;
  isEnabled?: boolean;
  conditions?: MessageRuleCondition;
  actions: MessageRuleAction;
  exceptionConditions?: MessageRuleCondition;
}

export interface UpdateMessageRulePayload {
  displayName?: string;
  priority?: number;
  isEnabled?: boolean;
  conditions?: MessageRuleCondition;
  actions?: MessageRuleAction;
  exceptionConditions?: MessageRuleCondition;
}

/** List all inbox message rules */
export async function listMessageRules(token: string, user?: string): Promise<GraphResponse<MessageRule[]>> {
  let result: GraphResponse<MessageRuleListResponse>;
  try {
    result = await callGraph<MessageRuleListResponse>(token, inboxRulesBase(user));
  } catch (err) {
    if (err instanceof GraphApiError) {
      return graphError(err.message, err.code, err.status);
    }
    return graphError(err instanceof Error ? err.message : 'Failed to list message rules');
  }
  if (!result.ok || !result.data) {
    return graphError(
      result.error?.message || 'Failed to list message rules',
      result.error?.code,
      result.error?.status
    );
  }
  return graphResult(result.data.value || []);
}

/** Get a single message rule by ID */
export async function getMessageRule(token: string, ruleId: string, user?: string): Promise<GraphResponse<MessageRule>> {
  try {
    return await callGraph<MessageRule>(
      token,
      `${inboxRulesBase(user)}/${encodeURIComponent(ruleId)}`
    );
  } catch (err) {
    if (err instanceof GraphApiError) {
      return graphError(err.message, err.code, err.status);
    }
    return graphError(err instanceof Error ? err.message : 'Failed to get message rule');
  }
}

/** Create a new inbox message rule */
export async function createMessageRule(
  token: string,
  payload: CreateMessageRulePayload,
  user?: string
): Promise<GraphResponse<MessageRule>> {
  try {
    return await callGraph<MessageRule>(token, inboxRulesBase(user), {
      method: 'POST',
      body: JSON.stringify(payload)
    });
  } catch (err) {
    if (err instanceof GraphApiError) {
      return graphError(err.message, err.code, err.status);
    }
    return graphError(err instanceof Error ? err.message : 'Failed to create message rule');
  }
}

/** Update an existing inbox message rule */
export async function updateMessageRule(
  token: string,
  ruleId: string,
  payload: UpdateMessageRulePayload,
  user?: string
): Promise<GraphResponse<MessageRule>> {
  try {
    return await callGraph<MessageRule>(token, `${inboxRulesBase(user)}/${encodeURIComponent(ruleId)}`, {
      method: 'PATCH',
      body: JSON.stringify(payload)
    });
  } catch (err) {
    if (err instanceof GraphApiError) {
      return graphError(err.message, err.code, err.status);
    }
    return graphError(err instanceof Error ? err.message : 'Failed to update message rule');
  }
}

/** Delete an inbox message rule */
export async function deleteMessageRule(token: string, ruleId: string, user?: string): Promise<GraphResponse<void>> {
  try {
    return await callGraph<void>(
      token,
      `${inboxRulesBase(user)}/${encodeURIComponent(ruleId)}`,
      { method: 'DELETE' },
      false
    );
  } catch (err) {
    if (err instanceof GraphApiError) {
      return graphError(err.message, err.code, err.status);
    }
    return graphError(err instanceof Error ? err.message : 'Failed to delete message rule');
  }
}
