#!/usr/bin/env node
/**
 * Writes `src/lib/git-commit.ts` with the current `git rev-parse HEAD`.
 * Run before publishing a release so error reporting can verify the build matches GitHub.
 */
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

let sha;
try {
  sha = execSync('git rev-parse HEAD', { cwd: root, encoding: 'utf8' }).trim();
} catch {
  console.error('embed-git-sha: not in a git repo or git failed; writing unknown');
  sha = 'unknown';
}

const content = `/**
 * Commit SHA for this build. Generated by scripts/embed-git-sha.mjs — do not edit by hand.
 */
export const COMMIT_SHA = '${sha}';
`;

const out = join(root, 'src', 'lib', 'git-commit.ts');
writeFileSync(out, content, 'utf8');
console.log('Wrote', out, 'COMMIT_SHA =', sha);
